### ISSUE TITLE
Explanation of Project structure

### ISSUE THREAD

**Issue by chintans** [Promact/guidelines#11]
We need to write details on what project structure we follow. It should also explain philosophy behind the structure.

**Comment by rushi216** [comment]
## Basic MVC/WebApi Project structure

We follow multiple project structure, In which every project have specific responsibility mentioned below

### {ProjectName}.Web:

**This is the root project or we can say startup project which will be responsible for holding all startup related logic as well as views, templates, client dependancies(javascripts).**

{ProjectName}.Core:

**Comment by rushi216** [comment]
# Basic MVC/WebApi Project structure

**We follow multiple project structure, In which every project have specific responsibility mentioned below**

### {ProjectName}.Web:

This is the root project or we can say startup project which will be responsible for holding all startup related logic as well as views, templates, client dependancies(javascripts).

### {ProjectName}.Core:

This project will hold MVC as well as WebAPI controllers, Action Filters, SignalR Hubs

We mostly put client server communication related code in this project, and don't put any business logic except that.

### {ProjectName}.Repository:

This project will hold all business logic related to application, in terms of {ModuleName}Repository.cs classes, where every logical module of application will have related repository.

### {ProjectName}.Util:

This project will hold basic utility classes which can be used for utilities like Emai, Encryption, Sms etc.

### {ProjectName}.DomainModel:

This project will hold all domain model classes which are directly connected to database (as we are using code first approach), As well as it will contain Entity Framework related configurations.

### {ProjectName}.Globalization:

If we need i18n related key-string mappings and stringconstants, then we will use this project to define all keyvalue pairs as well as resource files related to globalization in this project.

**Comment by rushi216** [comment]
@chintans @RiyaShah @iroshni please suggest corrections to above if any.

**Comment by iroshni** [comment]
### {ProjectName}.Test

If we are following practice of writing unit tests then we will use this project to define all lib wise tests.

**Comment by RiyaShah** [comment]
There should be separate unit test projects **{ProjectName}.Core.Test** and **{ProjectName}.Repository.Test**.

### {ProjectName}.Core.Test

It will hold unit tests related to Controllers, ActionFilters, SignalR Hubs, etc.

### {ProjectName}.Repository.Test

It will hold unit tests related to business logic of all the logical modules of the application.
