### ISSUE TITLE
Declare all member variables/properties at the top of a class, with static variables at the very top

### ISSUE THREAD

**Issue by RiyaShah** [Promact/guidelines#2]
public class Employee
{
    public static List<string> AnyListName;
    private int EmployeeId {get;set;};
    private string Name {get; set;};
    private int DepartmentId {get; set;};

```
// Constructor
public Employee()
{
    // ...
}
```

}

**Comment by chintans** [comment]
yes, We can call it Structure of a class.

**Comment by chintans** [comment]
@RiyaShah and @rushi216  This is now completed. Please provide your feedback

**Comment by RiyaShah** [comment]
@chintans 
You have declared public variable in camel casing with underscore. But usually we define public variables in pascal casing as defined underneath.

namespace FooBarApplication
{
    public class Foo
    {  
        private static string _nameOfClass;
        public static string NameOfMethods;
    }
}
