### ISSUE TITLE
Naming conventions

### ISSUE THREAD

**Issue by rushi216** [Promact/guidelines#5]
- PascalCase for classname
- camelCase for method arguments and local variables
- ALLCAPITAL for constant variables
- Always prefix interface with I, like IEmployeeRepository
- No abbrivations like Employee e
- No hungarian notations like strName
- No underscores in identifiers like emp_name

**Comment by chintans** [comment]
@rushi216 are these the only standards or there are more to be explored in detail? Do we really need to create a page for naming conventions? I think a good link should be sufficient. Provide your viewpoint on this please.

**Comment by rushi216** [comment]
@chintans there may be more naming conventions, https://msdn.microsoft.com/en-us/library/ms229002.aspx would be good enough if we want to provide a link for it.

**Comment by chintans** [comment]
I think in structure of class we already have covered bit of naming conventions already. Plus if we add this link to reading list. It should clear out the concept.
