### ISSUE TITLE
Avoid too many parameters  

### ISSUE THREAD

**Issue by RiyaShah** [Promact/guidelines#6]
Declare a class instead of too many parameters. Create a class that puts all these parameters together. This is generally a better design. 

**Good Practice:**
public void FunctionName(ShippingAddress shippingAddress,BillingAddress billingAddress)
{
//Code..
}

**Bad Practice:**
public void FunctionName(string shippingName, string shippingCity, 
       string shippingState, string shippingZip, string billingName, 
       string billingCity, string billingState, string billingZip)
{
//Code..
}

**Comment by chintans** [comment]
@RiyaShah I think this is Encapsulation concept. Should be covered in OOPs

**Comment by RiyaShah** [comment]
@chintans Yes it is the concept of Encapsulation.

**Comment by chintans** [comment]
Issue #8 should cover this topic very well. Therefore closing this issue for now.
